server:
  port: 8002
  servlet:
    context-path: /ledger-stock
spring:
  application:
    name: hakira-ledger-stock-service
  profiles:
    default: local
  cloud:
    nacos:
      server-addr: ${hakira.nacos.host}
      discovery:
        username: ${hakira.nacos.username}
        password: ${hakira.nacos.password}
        namespace: public
        ephemeral: true #nacos注册服务提供方设置为非临时实例
#日志监控的指定接口输出级别设置
logging:
  level:
    com.hakira.ledger.api.entry: debug
    com.hakira.ledger.api.stock: debug
# 激活Sentinel对OpenFeign的支持
feign:
  sentinel:
    enabled: true
management:
  endpoint:
    web:
      exposure:
        include: '*'
