#####MYSQL CONNECT CONFIG#####
hakira:
  db:
    host: mysql
    username: root
    password: 123456
  redis:
    host: redis
  nacos:
    host: 192.168.17.133:8848
    username: nacos
    password: nacos