server:
  port: 8080
  servlet:
    context-path: /hakira
spring:
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://${hakira.db.host}/hakira_gate?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${hakira.db.username}
    password: ${hakira.db.password}
    type: com.alibaba.druid.pool.DruidDataSource
  security:
    user:
      name: asdf
      password: qwer
    oauth2:
      client:
        registration:
          github:
            client-id: 9076ecee0a2ffe938b53
            client-secret: 9e3339b7e56baea091deb19f41b14d7903b0b27d
mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl