server:
  port: 8086

spring:
  application:
    name: hakira-ledger-task
  batch:
    job:
      enabled: false   # 不自动启动（由 Quartz 触发）
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          scheduler:
            instanceName: HakiraScheduler
          threadPool:
            threadCount: 5
